### ISSUE TITLE
st2actionrunner doesn't start in Jessie

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#156] opened 2016-02-06 21:49 UTC
Reported here: https://github.com/StackStorm/discussions/issues/142#issuecomment-180805926
To verify if it's still an issue in latest package version.

Probably an issue related to permissions, since `st2actionrunner` is the only one that should start from root.

**Comment by dennybaa** [comment] 2016-03-10 07:43
StackStorm/discussions#142 (comment) - was apparently could be caused by not full documentation available by that time.
Anyway I believe all actionrunner issues have been resolved with recent brushups. If it appears again let's get back to it... Meanwhile closing.

**Closed by dennybaa** 2016-03-10 07:43 UTC
Labels: bug, status:to be verified
