### ISSUE TITLE
Build fails for EL7

### ISSUE THREAD

**Issue by johann8384** [StackStorm/st2-packages#154] opened 2016-02-05 20:08 UTC
When I run:
```
docker-compose run --rm el7
```
The command fails with this error:
```
[ca1f0025][DEBUG]  Running /usr/bin/env ls -l /root/build on localhost
[ca1f0025][DEBUG]      total 48084
[ca1f0025][DEBUG]      -rw-r--r-- 1 root root 24713628 Feb  5 20:02 st2-1.4dev-1.x86_64.rpm
[ca1f0025][DEBUG]      -rw-r--r-- 1 root root 24519740 Feb  5 20:02 st2mistral-1.3.0-1.x86_64.rpm
[ca1f0025][DEBUG]  Finished in 0.011 seconds with exit status 0 (successful).
rake aborted!
Errno::ECONNREFUSED: Connection refused - connect(2) for "centos7test" port 22
/root/st2-packages/rake/build/upload_checkout.rake:18:in `block (5 levels) in <top (required)>'
/root/st2-packages/rake/remote.rb:72:in `instance_exec'
/root/st2-packages/rake/remote.rb:72:in `run'
/root/st2-packages/rake/build/upload_checkout.rake:16:in `block (4 levels) in <top (required)>'
/root/st2-packages/rake/pipeline.rb:27:in `instance_exec'
/root/st2-packages/rake/pipeline.rb:27:in `pipeline'
/root/st2-packages/rake/build/upload_checkout.rake:15:in `block (3 levels) in <top (required)>'
Tasks: TOP => default => setup:all => setup:install_artifacts => build:upload_to_testnode => upload_to_testnode.packages
(See full trace by running task with --trace)
```

**Comment by armab** [comment] 2016-02-06 15:44
From the log, it looks like packages were built, but `centos7test` Docker container where we install and smoke test just created packages - failed to start/missing something.

`docker-compose run el7 build` - this command was OK
`docker-compose run el7 test` - this command failed

Thanks for the report! I'll try to reproduce it after the weekends.

**Comment by dennybaa** [comment] 2016-02-08 10:00
Hey, Jonathan!

I could not repro ^^. My containers were not created (so it's a clean run). Here's the picture
![](https://i.gyazo.com/e16950615df6735168852027071b8e6a.png)
and
![](https://i.gyazo.com/d36de7781e9e37539e282f3b9269684a.png)

@johann8384 Could you please provide more details, what is your docker environment. I.e. do you run docker under virtualbox, or it's a standalone linux host, docker version, linux version etc.

**Comment by armab** [comment] 2016-02-09 18:44
Also @johann8384 apart of your environment, did you have problems building packages for other distros (`wheezy`/`jessie`/`trusty`)?

To verify if it's infra or code problem, can you please run: 
```sh
docker run --name centos7test --rm -it -v /sys/fs/cgroup:/sys/fs/cgroup quay.io/dennybaa/droneunit:centos7-systemd

docker exec -it centos7test bash -c 'systemctl start sshd'
docker exec -it centos7test bash -c 'systemctl status sshd'
```

----
If that ^^ fails, then it's infra limitation https://github.com/StackStorm/st2-packages/issues/31 described here: https://discuss.circleci.com/t/docker-with-centos7-systemd-container/885

**Comment by dennybaa** [comment] 2016-03-10 07:47
@johann8384 Sorry for not getting to this for so long! Actually systemd container couldn't be started normally on your new docker host (and mine as well), because `privileged` mode should be enabled.

https://github.com/dennybaa/st2-packages/blob/9e9abbfcaec17780bf4f3a3e2ca751fe29bbdca9/docker-compose.yml#L137

Feel free to re-open, meanwhile closing it.

**Closed by dennybaa** 2016-03-10 07:47 UTC
Labels: bug, status:to be verified

**Comment by dennybaa** [comment] 2016-03-11 06:10
NP, hope this solution solves it for you. But you're always welcome to get back :)
