### ISSUE TITLE
The st2 port is configured in the config file. But directly fixed in files such as service, socket, client, etc. 

### ISSUE THREAD

**Issue by huzunhao** [StackStorm/st2-packages#686] opened 2021-02-05 03:31 UTC
If you find an issue in packages, please file an issue and we'll have a look as soon as we can.
In order to expedite the process, it would be helpful to follow this checklist and provide
relevant information.

  * [ ] Operating system: `uname -a`, `./etc/lsb_release` or `cat /etc/redhat-release`
  * [ ] StackStorm version: `st2 --version`
  * [ ] Actual package versions of all packages (st2, st2web, st2chatops, nginx, mongo, rabbitmq-server)
    DEB: apt-cache policy ${PACKAGE_NAME} will give you the version of package.
    RPM: yum info ${PACKAGE_NAME} will you give the version of package.
    Note the exact name of mongo, nginx, rabbitmq changes based on OS.
  * [ ] [Contents of /etc/st2/st2.conf](url

)
  * [ ] Output of st2ctl status
  * [ ] Optional - Details about target box. E.g. vagrant box link or AWS AMI link.

#Issue details
my os is "Linux kcpm2 4.19.25-200.1.el7.bclinux.x86_64 #1 SMP Mon Aug 19 14:46:26 CST 2019 x86_64 x86_64 x86_64 GNU/Linux"
[root@kcpm2 /]# st2 --version
st2 3.3.0, on Python 2.7.5
![图片](https://user-images.githubusercontent.com/57519382/106985751-f81ed600-67a4-11eb-85eb-2a16e79288cd.png)
![图片](https://user-images.githubusercontent.com/57519382/106986086-957a0a00-67a5-11eb-999d-86fdac23b5e5.png)
![图片](https://user-images.githubusercontent.com/57519382/106986108-a32f8f80-67a5-11eb-82eb-08242d855b95.png)

**Comment by armab** [comment] 2021-02-05 13:11
Duplicate of https://github.com/StackStorm/st2/issues/3356 and https://github.com/StackStorm/st2/issues/2676

The fact that you have to configure host/port in 2 places: st2.conf and systemd service is definitely confusing.

We'd welcome any suggestions or contributions how to improve that.

**Comment by luislobo** [comment] 2021-06-09 23:38
Still cannot make it available on an Ubuntu 18.04. Where should I change the IPs?

**Closed** 2021-10-06 23:47 UTC
Labels: bug, enhancement, help wanted
